### ISSUE TITLE
Does it support Cancan?

### ISSUE THREAD

**Issue by FX-HAO** [ColDog/graphql-api#1]
In my case, i am using cancan for my api authorization. It's best to support Cancan that i can maintain a single-codebase.

**Comment by FX-HAO** [comment]
And I am using Rails 4.2.6, so now it is not compatible with Rails 4?

**Comment by ColDog** [comment]
@FX-HAO I just updated the gem to version 0.1.5 which add's support for rails 4.2 and up. Let me know if you have any issues I would be happy to help you with them, sorry for the delay in responding.

As far as CanCan, there currently is no support bundled with the gem. I would be interested in hearing how you think this should be built into it.

**Comment by FX-HAO** [comment]
Thanks for your response. 

At first of all, i think that it's a top priority to support Delay.

If I achieve this feature, would you be open to accepting a PR?

**Comment by ColDog** [comment]
Definitely! I am excited to work on this project and get it going, relay support should not be too hard to get running. I think it's more just testing and making sure it works.
