### ISSUE TITLE
The policy class constructor has two args, but resolvers are try instantiate with three

### ISSUE THREAD

**Issue by niltonvasques** [ColDog/graphql-api#3]
The policy class initializer has only two arguments:

```ruby
    def initialize(ctx, model)
```

However the instantiation is passing three in many resolvers:

```ruby
       def call(inputs, ctx)
         if @policy_class
           policy = @policy_class.new(ctx[:current_user], nil, ctx)
```

**Comment by ColDog** [comment]
Thanks for the issue! I think the code for the policies was a little rushed and ended up making some mistakes. 0.1.6 should have these latest changes as well as some more tests.

I haven't had the time to really dig into the usages of the policy objects in any projects yet so please let me know if the api could be any cleaner in any places.

Thanks again, and feel free to let me know if these changes don't meet your requirements.

**Comment by niltonvasques** [comment]
I'm working in a project with a lot of models/controllers with very well fine tune policy system. And I'm thinking in give a try with graphql, to dry up too many routes and give a better synchronization solution to mobile clients. So if I've some suggestions along that task I will let you know. 

And really thanks for the fixes on that issue asap. :100:
